owner: Dein-Ticket-Shop
repo: status

sites:
  - name: Dein-Ticket.Shop
    url: https://dein-ticket.shop
  - name: Klecks
    url: https://klecks.dein-ticket.shop
  - name: Klecks Admin
    url: https://klecks.admin.dein-ticket.shop
  - name: Klecks VVK
    url: https://klecks.vvk.dein-ticket.shop
  - name: Login
    url: https://login.dein-ticket.shop

status-website:
  # cname: demo.upptime.js.org
  # baseUrl: /your-repo-name
  logoUrl: https://avatars.githubusercontent.com/u/127296773
  name: Dein-Ticket-Shop Status
  introTitle: Dein-Ticket-Shop Status
  introMessage: This is the status page for Dein-Ticket-Shop.
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://dein-ticket.shop
