owner: Dein-Ticket-Shop
repo: status
sites:
  - name: Dein-Ticket.Shop
    url: https://dein-ticket.shop
  - name: Login
    url: https://login.dein-ticket.shop
  - name: Kleinkunstverein Klecks e.V. - Verkaufsseite
    url: https://klecks.dein-ticket.shop
  - name: Kleinkunstverein Klecks e.V. - Admin-Bereich
    url: https://klecks.admin.dein-ticket.shop
  - name: Kleinkunstverein Klecks e.V. - Vorverkauf
    url: https://klecks.vvk.dein-ticket.shop
  - name: Kunstquartier Allgäu - Verkaufsseite
    url: https://kqa.dein-ticket.shop
  - name: Kunstquartier Allgäu - Admin-Bereich
    url: https://kqa.admin.dein-ticket.shop
  - name: Kunstquartier Allgäu - Vorverkauf
    url: https://kqa.vvk.dein-ticket.shop
  - name: Alpe Müllers Berg - Verkaufsseite
    url: https://alpe-muellers-berg.dein-ticket.shop
  - name: Alpe Müllers Berg - Admin-Bereich
    url: https://alpe-muellers-berg.admin.dein-ticket.shop
  - name: Alpe Müllers Berg - Vorverkauf
    url: https://alpe-muellers-berg.vvk.dein-ticket.shop
status-website:
  logoUrl: https://avatars.githubusercontent.com/u/127296773
  name: Dein-Ticket-Shop Status
  introTitle: Dein-Ticket-Shop Status
  introMessage: This is the status page for Dein-Ticket-Shop.
  baseUrl: /status
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://dein-ticket.shop
