owner: Dein-Ticket-Shop
repo: status
sites:
  - name: Dein-Ticket.Shop
    url: https://dein-ticket.shop
  - name: Login
    url: $URL_LOGIN
  - name: Online-Shop
    url: $URL_FRONTEND
  - name: Admin-Bereich
    url: $URL_BACKEND
  - name: Vorverkauf
    url: $URL_VVK
  - name: API
    url: $URL_API
    expectedStatusCodes:
      - 404
#  - name: Testsystem
#    url: $URL_TEST
#  - name: Testsystem Login
#    url: $URL_TEST_LOGIN
#  - name: Testsystem Online-Shop
#    url: $URL_TEST_FRONTEND
#  - name: Testsystem Admin-Bereich
#    url: $URL_TEST_BACKEND
#  - name: Testsystem Vorverkauf
#    url: $URL_TEST_VVK
#  - name: Testsystem API
#    url: $URL_TEST_API
#    expectedStatusCodes:
#      - 404
status-website:
  logoUrl: https://avatars.githubusercontent.com/u/127296773
  name: Dein-Ticket-Shop Status
  introTitle: Dein-Ticket-Shop Status
  introMessage: This is the status page for Dein-Ticket-Shop.
  baseUrl: /
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://dein-ticket.shop
